"""empty message

Revision ID: 3d3f005f9b89
Revises: ed87ba35ff19
Create Date: 2021-09-12 22:22:31.608367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3f005f9b89'
down_revision = 'ed87ba35ff19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('punch', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'punch', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'punch', type_='foreignkey')
    op.drop_column('punch', 'employee_id')
    # ### end Alembic commands ###
