"""empty message

Revision ID: 84becb5e576d
Revises: 781c37d3e9f1
Create Date: 2021-09-23 03:01:58.242174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84becb5e576d'
down_revision = '781c37d3e9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
