"""empty message

Revision ID: c459bb1b222b
Revises: b48444d128ba
Create Date: 2021-09-11 01:07:15.234401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c459bb1b222b'
down_revision = 'b48444d128ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'profile_id')
    # ### end Alembic commands ###
