"""empty message

Revision ID: df01221b8fc1
Revises: e71ed3765c06
Create Date: 2021-09-17 01:02:53.265094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df01221b8fc1'
down_revision = 'e71ed3765c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer', 'role')
    op.drop_column('employer', 'hourly_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer', sa.Column('hourly_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('employer', sa.Column('role', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
